Testing with pytest
barbagroup/essential_skills_RRC pull request #49
Opened 2017-01-16 20:09 UTC by ncclementi

Add `.md` with testing session following what we showed in the workshop session.
Add pytest entry to `mkdocs.yml`

2017-01-25 16:04 UTC, gforsyth commented on mkdocs.yml
> +        - Pytest: testing.md
should be `testing/testing.md`

2017-01-25 16:17 UTC, gforsyth requested changes
Hey @ncclementi -- thanks for putting this together! There are a few typos and inconsistencies that I pointed out and one part that I think we need to rework a little bit.  

Also in the interests of proper Python style, there should be spaces before and after every operator (except `**`) and also spaces after every comma.

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +def dot_product (a,b):
no space before parens

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +Right under our function we can add our first test. What can be a good test?
I think change this to read "What's a good test?"

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +Let's try checking if the dot product of zero's vectors returns zero.
No `'s` after zero

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +    a=[0,0]
spaces before and after operators

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +`my_dot_product.py`. If you are using `nano` type in a terminal:
below we're running `dot_product.py` but up here it's `my_dot_product.py` -- I'm fine with either but it should be consistent.

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +with different length? Let's write a test and try it out.
I think this section needs to be reworked. We shouldn't talk about `pytest.raises(AssertionError)` until we've added an assertion to the script. 

I would first add the two tests (`a < b` and `b < a`) like 

```def test_dot_a_lt_b():
    a = [1, 2]
    b = [1, 1, 2]
    assert dot(a, b) == 3
```

the `b < a` test will fail due to an indexing error. 
Then the lesson is that this test has exposed a problem with the function -- we need to add an assertion that the arrays are the same length. Then we can talk about `pytest.raises`

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +expected value we will re-designed our test in the following way:
*redesign

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +For a better organization of your code we strongly recomment having your tests
*recommend

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +in a separate file. In the example we've been working a way to do that can be:
*For the current example we can do the following:

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +case you will `import pytest` and `from dot_product import dot`, therefore your file will look likes:
look *like

2017-01-25 16:17 UTC, gforsyth commented on docs/testing/testing.md
> +`pytest test_dot.py`.
If there's a test file that begins with `test_` then you only need to run `pytest` without any other arguments and pytest will detect it.

2017-01-25 16:40 UTC, ncclementi commented on docs/testing/testing.md
> +with different length? Let's write a test and try it out.
Ok, that sounds better, I was just following what we did in the course but definitely I agree with you. I'll work on it.

2018-11-12 19:22 UTC, ncclementi commented
@gforsyth I know this is old, but would you review this so we can merge it? 

Thanks

2020-03-25 14:46 UTC, merged